import Link from "next/link";
import { ArrowRight, Check, ChefHat, CircleDollarSign, Copy, GripVertical, Layers3, Pencil, Search, Smartphone, Sparkles, Store, Trash2, UtensilsCrossed } from "lucide-react";

const features = [
  { title: "Add & edit dishes", text: "Name, price, description, category and dietary tags—all in one focused form.", icon: Pencil, style: "md:col-span-2 md:row-span-2 bg-[#1a1a1a] text-white" },
  { title: "Real-time publishing", text: "Save once. Every customer sees the change instantly.", icon: Smartphone, style: "bg-[#e8ddcf]" },
  { title: "Bulk actions", text: "Upload by CSV or copy menus between locations.", icon: Copy, style: "bg-[#dfe5d9]" },
  { title: "Dynamic pricing", text: "Schedule service-based prices without duplicating dishes.", icon: CircleDollarSign, style: "md:col-span-2 bg-[#d97e3a] text-white" },
];
const plans = [
  { name: "Starter", price: "$29", note: "For independent restaurants", items: ["2 locations", "200 menu items", "Basic analytics", "Email support"] },
  { name: "Professional", price: "$79", note: "For growing restaurant groups", featured: true, items: ["10 locations", "Unlimited menu items", "Advanced analytics", "Priority support", "API access"] },
  { name: "Enterprise", price: "Custom", note: "For multi-brand operations", items: ["Unlimited locations", "White-label branding", "Dedicated account manager", "Custom integrations"] },
];

export default function Home() {
  return <main className="overflow-hidden">
    <nav className="sticky top-0 z-50 border-b bg-[#f8f7f5]/90 backdrop-blur-xl"><div className="wrap flex h-16 items-center justify-between"><Link href="/" className="brand"><span className="logo"><UtensilsCrossed size={18}/></span>MenuFlow</Link><div className="hidden items-center gap-8 text-sm font-semibold md:flex"><a href="#features">Features</a><a href="#layouts">Customer menus</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></div><div className="flex items-center gap-3"><Link href="/login" className="hidden text-sm font-semibold sm:block">Admin login</Link><Link href="/login" className="btn">Start free trial <ArrowRight size={15}/></Link></div></div></nav>
    <section className="hero"><div className="circle circle-one"/><div className="circle circle-two"/><div className="wrap relative grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><span className="eyebrow"><Sparkles size={14}/> Built for busy restaurants</span><h1>Your menu,<br/><span className="text-accent">always fresh.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-text">Update dishes in seconds. Customers see changes instantly. No printing. No hassle.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="btn btn-lg">Start free trial <ArrowRight size={17}/></Link><Link href="/menu" className="btn-secondary btn-lg">View live menu</Link></div><p className="mt-5 flex items-center gap-2 text-sm text-muted-text"><Check className="text-sage" size={17}/> Launch your first menu without a credit card</p></div><Dashboard/></div></section>
    <section className="border-y bg-[#efeeeb]"><div className="wrap grid grid-cols-2 divide-x divide-y md:grid-cols-5 md:divide-y-0">{[["2,847","active restaurants"],["14.2M","menu views monthly"],["98.7%","uptime SLA"],["$340K","saved in printing"],["45 sec","average update"]].map(x=><div className="px-4 py-7 text-center" key={x[1]}><strong className="font-heading text-xl sm:text-2xl">{x[0]}</strong><p className="mt-1 text-xs text-muted-text">{x[1]}</p></div>)}</div></section>
    <section id="features" className="section"><div className="wrap"><SectionHead tag="One calm command center" title="Manage your menu in minutes" copy="From a quick sold-out toggle to a full seasonal launch, every action stays simple."/><div className="grid gap-4 md:grid-cols-4 md:grid-rows-2">{features.map(({title,text,icon:Icon,style})=><article className={`feature-card ${style}`} key={title}><Icon size={25}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
    <section className="section bg-white"><div className="wrap grid gap-12 lg:grid-cols-2"><div><span className="eyebrow">Fits the way you serve</span><h2>For every restaurant type</h2><p className="section-copy">Run one neighborhood café or coordinate ten dining rooms. MenuFlow keeps each menu accurate without slowing your team down.</p></div><div className="divide-y border-y">{[[Store,"Casual dining","Pizzerias, taco shops and burger joints"],[Sparkles,"Fine dining","Tasting menus, pairings and nightly courses"],[ChefHat,"Cafés & bakeries","Fresh batches, pastry rotations and seasonal specials"],[UtensilsCrossed,"Food trucks & popups","Rotating menus, events and flexible pricing"]].map(([I,t,d])=>{const Icon=I as typeof Store;return <div className="type-row" key={String(t)}><Icon/><div><h3>{String(t)}</h3><p>{String(d)}</p></div><ArrowRight/></div>})}</div></div></section>
    <section id="layouts" className="section"><div className="wrap"><SectionHead tag="Guest experience" title="Beautiful on every screen" copy="Searchable, fast and designed to make choosing dinner feel effortless."/><div className="layout-showcase"><div className="phone"><div className="phone-top"><span>Casa Table</span><Search size={13}/></div><div className="flex gap-1 overflow-hidden p-3">{["All","Mains","Vegan"].map(x=><span className="chip" key={x}>{x}</span>)}</div><div className="grid grid-cols-2 gap-2 px-3">{["Burrata","Rigatoni","Sea bass","Olive cake"].map((x,i)=><div className="menu-tile" key={x}><div className={`food-shape f${i}`}/><b>{x}</b><span>${[14,24,29,11][i]}</span></div>)}</div></div><div className="layout-copy">{[["01","Classic grid","Visual, scannable cards for casual menus with quick prices and dietary details."],["02","Category tabs","Guests jump directly from appetizers to mains and desserts."],["03","Elegant list","Longer descriptions and spacious typography for considered dining."]].map((x,i)=><div key={x[0]}>{i>0&&<div className="divider"/>}<span className="number">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></div></section>
    <section className="quote"><div className="wrap"><p className="text-accent">WHAT RESTAURANTS SAY</p><blockquote>“Updating daily specials used to be a nightmare—now it takes 30 seconds. MenuFlow saved us thousands.”</blockquote><div className="mt-8 flex items-center gap-3"><span className="avatar">MG</span><div><b>Maria Gonzalez</b><p className="text-sm text-gray-400">Owner, Casa Blanca Restaurant</p></div></div><div className="mt-10 flex gap-2"><span className="h-1 w-12 bg-accent"/><span className="h-1 w-6 bg-gray-700"/><span className="h-1 w-6 bg-gray-700"/></div></div></section>
    <section id="pricing" className="section bg-white"><div className="wrap"><SectionHead tag="Simple pricing" title="Grow without menu limits" copy="Start with the tools you need today. Move up when your operation does."/><div className="grid overflow-hidden rounded-lg border lg:grid-cols-3">{plans.map(p=><article className={`plan ${p.featured?"featured":""}`} key={p.name}>{p.featured&&<span className="popular">MOST POPULAR</span>}<h3>{p.name}</h3><p>{p.note}</p><div className="price">{p.price}{p.price.startsWith("$")&&<small>/month</small>}</div><Link href="/login" className={p.featured?"btn justify-center":"btn-secondary justify-center"}>{p.price==="Custom"?"Request a demo":"Start free trial"}</Link><ul>{p.items.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></article>)}</div></div></section>
    <section id="faq" className="section"><div className="wrap grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><span className="eyebrow">FAQ</span><h2>Answers for your team</h2><p className="section-copy">Everything you need to know before putting your first live menu online.</p></div><div className="divide-y border-y">{[["Will customers need to download an app?","No. Your menu opens in any mobile or desktop browser and updates automatically."],["Can staff mark an item as sold out?","Yes. Authorized staff can change availability instantly without editing the dish."],["Can I manage multiple locations?","Yes. Professional and Enterprise plans let you copy items and manage menus by location."],["Can I import an existing menu?","Yes. Bulk CSV upload makes it easy to bring over names, descriptions, categories and prices."]].map(x=><details className="faq" key={x[0]}><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</div></div></section>
    <section className="px-4 pb-4"><div className="cta"><div><span className="eyebrow light">Your next service starts here</span><h2>Serve a menu that<br/>never falls behind.</h2></div><div><p>Join restaurants replacing reprints, crossed-out prices and outdated PDFs with one live menu.</p><Link href="/login" className="btn bg-white text-[#1a1a1a]">Start free trial <ArrowRight size={16}/></Link></div></div></section>
    <Footer/>
  </main>;
}

function SectionHead({tag,title,copy}:{tag:string;title:string;copy:string}) { return <div className="section-head"><span className="eyebrow">{tag}</span><h2>{title}</h2><p>{copy}</p></div> }
function Dashboard(){return <div className="dashboard"><div className="dash-top"><div className="flex items-center gap-2 font-bold"><span className="logo size-7"><UtensilsCrossed size={14}/></span>Casa Table</div><span className="status"><span/>Live</span></div><div className="grid grid-cols-[105px_1fr] sm:grid-cols-[125px_1fr]"><aside className="dash-side"><p>MENU</p>{["All dishes","Starters","Mains","Desserts"].map((x,i)=><div key={x} className={i===0?"active":""}><Layers3 size={12}/>{x}</div>)}</aside><div className="p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><span className="text-[9px] text-muted-text">DINNER MENU</span><h3 className="font-heading font-bold">18 dishes</h3></div><button className="rounded bg-accent px-3 py-2 text-[9px] font-bold text-white">+ Add dish</button></div><div className="space-y-2">{[["Charred burrata","Starters","$14"],["Wild mushroom rigatoni","Mains","$24"],["Citrus olive cake","Desserts","$11"]].map((d,i)=><div className="dish-row" key={d[0]}><GripVertical size={12}/><span className={`dish-thumb d${i}`}><ChefHat size={14}/></span><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-bold">{d[0]}</p><p className="text-[8px] text-muted-text">{d[1]} · Available</p></div><b className="text-[10px]">{d[2]}</b><Pencil size={11}/><Trash2 size={11}/></div>)}</div><div className="mt-4 grid grid-cols-3 gap-2">{[["Views","12.4K"],["Updates","42"],["Uptime","99.9%"]].map(x=><div className="metric" key={x[0]}><b>{x[1]}</b><span>{x[0]}</span></div>)}</div></div></div></div>}
function Footer(){return <footer><div className="wrap grid gap-10 py-14 md:grid-cols-[2fr_1fr_1fr_1fr]"><div><Link href="/" className="brand"><UtensilsCrossed size={20}/>MenuFlow</Link><p className="mt-4 max-w-xs text-sm text-muted-text">The live menu platform for independent restaurants and growing groups.</p></div>{[["Product","Features","Customer menus","Pricing"],["Company","About","Contact","Security"],["Account","Admin login","Live menu","Support"]].map(c=><div key={c[0]}><b>{c[0]}</b>{c.slice(1).map(x=><a href={x==="Admin login"?"/login":x==="Live menu"?"/menu":"#"} key={x}>{x}</a>)}</div>)}</div><div className="border-t py-5"><div className="wrap flex justify-between text-xs text-muted-text"><span>© 2026 MenuFlow</span><span>Privacy · Terms · Accessibility</span></div></div></footer>}
